baseURL = "https://example.org/"
title = "结痂行会"
languageCode = "zh"
DefaultContentLanguage = "zh"
enableInlineShortcodes = true
theme = "vnovel"
enableRobotsTXT = true
hasCJKLanguage = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
paginator_pages = "5"

# Site logo.
logo = "/img/logo.webp"

  [params.homepage_meta_tags]
    meta_description = "疮海夜夜狂谭。"
    meta_og_title = "结痂行会"
    meta_og_type = "website"
    meta_og_image = "https://vnovel.pages.dev/img/thumbnail.png"
    
# ---------- 搜尋所需的 output format（加入到你的 config.toml） ----------
[outputs]
  # 讓首頁輸出 HTML 與 JSON（會產生 public/index.json）
  home = ["HTML", "JSON"]

[outputFormats]
  [outputFormats.JSON]
    name = "JSON"
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true
    notAlternative = true
